-- Project registration and project-scoped browser policies for Sabel_072026.
insert into public.projects (project_id,client_name,event_type,total_seats,reserved_family_seats)
values ('Sabel_072026','Sabel & Jaycee','Wedding',400,50)
on conflict (project_id) do update set client_name=excluded.client_name,event_type=excluded.event_type,total_seats=excluded.total_seats,reserved_family_seats=excluded.reserved_family_seats,updated_at=now();

drop policy if exists "Public reads Sabel project" on public.projects;
create policy "Public reads Sabel project" on public.projects for select to anon using (project_id='Sabel_072026');
drop policy if exists "Dashboard updates Sabel project" on public.projects;
create policy "Dashboard updates Sabel project" on public.projects for update to anon using (project_id='Sabel_072026') with check (project_id='Sabel_072026');
drop policy if exists "Public reads Sabel RSVPs" on public.rsvp_submissions;
create policy "Public reads Sabel RSVPs" on public.rsvp_submissions for select to anon using (project_id='Sabel_072026');

-- Capacity enforcement must calculate from the writable base column.
-- total_party_size is generated by PostgreSQL and cannot be read or assigned
-- by a BEFORE INSERT trigger.
create or replace function public.set_rsvp_review_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  public_capacity integer;
  currently_reserved integer;
  incoming_party_size integer;
begin
  incoming_party_size := coalesce(new.additional_guests, 0) + 1;

  select total_seats - reserved_family_seats
    into public_capacity
  from public.projects
  where project_id = new.project_id
  for update;

  if public_capacity is null then
    raise exception 'Invalid project ID';
  end if;

  select coalesce(sum(total_party_size), 0)
    into currently_reserved
  from public.rsvp_submissions
  where project_id = new.project_id;

  if currently_reserved + incoming_party_size > public_capacity then
    if new.project_id = 'Sabel_072026' then
      raise exception 'Requested party exceeds remaining RSVP capacity';
    end if;
    new.review_status := 'manual_review';
  else
    new.review_status := 'received';
  end if;

  return new;
end;
$$;

drop trigger if exists check_rsvp_capacity_before_insert on public.rsvp_submissions;
drop trigger if exists set_rsvp_review_status_before_insert on public.rsvp_submissions;
create trigger set_rsvp_review_status_before_insert
before insert on public.rsvp_submissions
for each row execute function public.set_rsvp_review_status();

revoke execute on function public.set_rsvp_review_status()
from public, anon, authenticated;
